### ISSUE TITLE
Error: Not a valid chart repository or cannot be reached

### ISSUE THREAD

**Issue by atyourservers** [Azure-Samples/helm-charts#37]
When trying to add the repository using the command _helm repo add "azure-samples" https://azure-samples.github.io/helm-charts_ I get the following error:

> Error: Looks like "https://azure-samples.github.io/helm-charts" is not a valid chart repository or cannot be reached: Get https://azure-samples.github.io/helm-charts/index.yaml: read tcp 10.130.1.69:47504->185.199.109.153:443: read: connection reset by peer

I don't get this when adding other repositories. Seems like there is something wrong with this repository...?

**Comment by neilpeterson** [comment]
@atyourservers sorry that you are having this issue. I am unable to reproduce, everything works well for me. Could it possibly be a transient network issue?

**Comment by atyourservers** [comment]
Perhaps... Wouldn't know how to find out for sure/troubleshoot...? I can add other repositories without any issues, such as _https://svc-catalog-charts.storage.googleapis.com_ and _https://kubernetescharts.blob.core.windows.net/azure_.
